SELECT  D.INDEKS, D.IME, D.PREZIME, COALESCE(AVG(I.OCENA * 1.0), 0) AS PROSEK
FROM    DA.DOSIJE D LEFT JOIN DA.ISPIT I ON I.INDEKS = D.INDEKS
WHERE D.INDEKS / 10000 = 2016
GROUP BY D.INDEKS, D.IME, D.PREZIME;