SELECT NAZIV, 
    COALESCE(
        AVG(CASE WHEN STATUS='o' AND OCENA>5 THEN OCENA*1.0 END)
    ,0) PROSEK_OCENA,
    100.0 * SUM(CASE WHEN I.OCENA > 5 AND I.STATUS='o' THEN 1 ELSE 0 END) / COUNT(*) PROCENAT_USPESNOSTI
FROM DA.PREDMET P JOIN DA.ISPIT I ON I.IDPREDMETA=P.ID 
WHERE SKGODINA=2015
GROUP BY NAZIV;