SELECT 
    UP.IDUSLOVNOGPREDMETA,
    P.NAZIV 
FROM DA.USLOVNIPREDMET UP JOIN DA.PREDMET P ON P.ID=UP.IDUSLOVNOGPREDMETA
WHERE UP.IDPREDMETA= 1930 AND EXISTS (
    SELECT *
    FROM DA.ISPIT I JOIN DA.DOSIJE D ON D.INDEKS=I.INDEKS 
                    JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID=D.IDPROGRAMA
    WHERE OCENA=10 AND STATUS='o' AND YEAR(DATPOLAGANJA)<2018 AND SP.IDNIVOA=1
        AND I.IDPREDMETA=UP.IDUSLOVNOGPREDMETA
);