SELECT IME, PREZIME, D.INDEKS, COUNT(*) NEUSPESNA_POLAGANJA
FROM DA.DOSIJE D JOIN DA.ISPIT I ON D.INDEKS=I.INDEKS 
    JOIN DA.STUDIJSKIPROGRAM SP ON SP.ID=D.IDPROGRAMA
WHERE STATUS='o' AND OCENA=5 AND SP.NAZIV='Informatika'
GROUP BY IME, PREZIME, D.INDEKS
ORDER BY NEUSPESNA_POLAGANJA DESC;