SELECT I.INDEKS, I.OCENA, I.DATPOLAGANJA
FROM DA.ISPIT I 
WHERE I.STATUS='o' AND OCENA>5 AND 
    'Informatika' = (
        SELECT SP.NAZIV
        FROM DA.STUDIJSKIPROGRAM SP JOIN DA.DOSIJE D ON SP.ID=D.IDPROGRAMA
        WHERE D.INDEKS=I.INDEKS
    )AND 
    I.DATPOLAGANJA = (
        SELECT MIN(I2.DATPOLAGANJA)
        FROM DA.ISPIT I2 
        WHERE I2.INDEKS=I.INDEKS AND I2.STATUS='o' AND I2.OCENA>5
    );
