SELECT D.IME, D.PREZIME, NAZIV, I.DATPOLAGANJA
FROM DA.DOSIJE D JOIN DA.ISPIT I ON D.INDEKS=I.INDEKS
                 JOIN DA.PREDMET P ON P.ID=I.IDPREDMETA
WHERE I.STATUS='o' AND OCENA>5 AND I.DATPOLAGANJA = (
        SELECT MAX(I2.DATPOLAGANJA)
        FROM DA.ISPIT I2
        WHERE I2.INDEKS = I.INDEKS AND I2.STATUS = 'o' AND I2.OCENA > 5
    );