SELECT INDEKS, OCENA
FROM DA.ISPIT I
WHERE STATUS='o' AND OCENA BETWEEN 6 AND 9 AND IDPREDMETA IN (
            SELECT ID FROM DA.PREDMET WHERE NAZIV = 'Programiranje 1'
        )
FETCH FIRST 10 ROWS ONLY;