SELECT I.INDEKS,
    (SELECT IME FROM DA.DOSIJE D WHERE D.INDEKS=I.INDEKS),
    (SELECT PREZIME FROM DA.DOSIJE D WHERE D.INDEKS=I.INDEKS),
    I.OCENA 
FROM DA.ISPIT I
WHERE STATUS='o' AND SKGODINA=2016 AND OZNAKAROKA='jan2' AND 
    'Programiranje 1' = (
        SELECT P.NAZIV
        FROM DA.PREDMET P 
        WHERE P.ID=I.IDPREDMETA
    );